name: Validate code style
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
concurrency:
  group: style_${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  style:
    name: Code style validations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: 'actions/checkout@v3'

      - name: Configure Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Retrieve npm cache
        uses: 'actions/cache@v3'
        with:
          path: ${{ github.workspace }}/node_modules
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
            ${{ runner.os }}-node-

      - name: Install Node packages
        run: npm ci

      - uses: EPMatt/reviewdog-action-prettier@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning

      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: 'lib/**/*.js'